export const ActionTypes = {
  SELECT_EVENT: "SELECT_EVENT",
  CREATE_NEW_EVENT: "CREATE_NEW_EVENT",
  UPDATE_EVENT: "UPDATE_EVENT",
  SAVE_NEW_EVENT: "SAVE_NEW_EVENT",
  DELETE_EVENT: "DELETE_EVENT",

  // Syncing action types
  UPDATE_SUCCESSFUL: "UPDATE_SUCCESSFUL",
  SAVE_SUCCESSFUL: "SAVE_SUCCESSFUL",
  DELETE_SUCCESSFUL: "DELETE_SUCCESSFUL",
};
